name: Python CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code

      -name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        
        
